### ISSUE TITLE
MetadataException: Error getting parameters for storedProcedure

### ISSUE THREAD

**Issue by adamclifford** [docevaad/Chain#137]
When I try and execute a stored procedure I get the error: Invalid column name 'is_nullable'.

I have tracked it down to the SqlServerMetadataCache.TableFunctionMetadata => GetParameters.

The is_nullable return is not valid from the sys.parameters table and should be pulled from the sys.types table

**Comment by Grauenwolf** [comment]
Interesting. I'm not seeing that bug on my machine, so it probably is a SQL Server version issues.

What version of SQL Server are you using?

**Comment by adamclifford** [comment]
SQL Server 2012, version 11.0.5623 if that helps.

**Comment by Grauenwolf** [comment]
Yes, thank you.

Now I need to figure out if I can reproduce the bug in SQL Server 2016 using just compatibility levels or if I need to setup a VM. 

In the mean time, your patch is in the latest NuGet package.

Jonathan 

-----Original Message-----
