### ISSUE TITLE
An error occurred with OUTPUT clause when a trigger is on the table

### ISSUE THREAD

**Issue by mikilion** [docevaad/Chain#170]
Chain commands as Insert, Update or Delete with return value generate a error when a trigger is on the table:

`The target table 'TableName' of the DML statement cannot have any enabled triggers if the statement contains an OUTPUT clause without INTO clause`

**Comment by Grauenwolf** [comment]
Can you show me the line of code you used to trigger this error? 

I think I know how to fix it, but I want to make sure I address your specific use case.

**Comment by Grauenwolf** [comment]
And just to verify, are you using SQL Server?

**Comment by mikilion** [comment]
The error occur by Chain commands as these:
```
dataSource.Upsert("TableName", entity).WithRefresh()...
dataSource.Insert("TableName", entity).ToInt32()...
dataSource.Insert("TableName", entity).ToObject()...
```
I'm using SQL Server 2016.

**Comment by Grauenwolf** [comment]
Dev notes. 

1. Detect tables with triggers: `select * from sys.triggers`
2. If they exist, switch to using a temp table in the SQL generation as per http://stackoverflow.com/questions/13198476/cannot-use-update-with-output-clause-when-a-trigger-is-on-the-table

**Comment by Grauenwolf** [comment]
I can provide a behavior override as an advanced feature, but it really should "just work" regardless if you have triggers or not. Otherwise adding a trigger to a pre-existing table becomes a breaking change.

**Comment by mikilion** [comment]
Why don't we distinguish COUNT from COUNT_BIG?
Count()
CountBig()

**Comment by Grauenwolf** [comment]
Inserts are now fixed. But they require a change to the Core library, so it won't be published until version 1.1.

Still need to port the fix update, delete, and maybe upsert.

**Comment by Grauenwolf** [comment]
Update/Delete are done. Confirmed that Upsert has the same bug.

**Comment by Grauenwolf** [comment]
This feature will be part of this week's Chain 1.1. release.
