### ISSUE TITLE
DeleteMany Command Builder

### ISSUE THREAD

**Issue by mikilion** [docevaad/Chain#171]
Provide the `.WithFilter(...)` method to the Delete command.

**Comment by Grauenwolf** [comment]
This is closely related to task: https://github.com/docevaad/Chain/issues/106

**Comment by Grauenwolf** [comment]
The commands will probably end up being 

* `.DeleteBatch(table, filterObject)`
* `.DeleteBatch(table, whereExpression, argumentObject)`

This way it is clearer that you want to delete multiple rows, not just one.

Dev notes: Make sure to include a path for soft deletes.

**Comment by Grauenwolf** [comment]
Also related to #105

**Comment by Grauenwolf** [comment]
- `ds.DeleteMany(tableName, whereClause, argumentValue, options)`
- `ds.DeleteMany(tableName, whereClause, options)`
- `ds.DeleteMany(tableName, filterValue, options)`

See #105 for UpdateMany.

**Comment by Grauenwolf** [comment]
This feature will be part of this week's Chain 1.1. release.
