### ISSUE TITLE
SoftDeleteRule issue

### ISSUE THREAD

**Issue by mikilion** [docevaad/Chain#173]
When the soft delete rule on the "select" or "delete" operations is determined, it has effect on the "update" and "insert" operations as well.

**Comment by Grauenwolf** [comment]
Can you elaborate?

**Comment by Grauenwolf** [comment]
Ugh, one missing set of parens and the whole thing is screwed. I'll have a fixed posted shortly.

**Comment by Grauenwolf** [comment]
Also, I found out why you are seeing this but my test wasn't. The test was using 

```
        [IgnoreOnInsert, IgnoreOnUpdate]
        public int? DeletedByKey
        {
            get { return Get<int?>(); }
            set { Set(value); }
        }

        [IgnoreOnInsert, IgnoreOnUpdate]
        public DateTime? DeletedDate
        {
            get { return Get<DateTime?>(); }
            set { Set(value); }
        }

        [IgnoreOnInsert, IgnoreOnUpdate]
        public bool DeletedFlag
        {
            get { return Get<bool>(); }
            set { Set(value); }
        }
```

If you don't have those properties defined on your model, then you trigger the bug in the SQL generator. The tests have been updated to take this into consideration.

**Comment by Grauenwolf** [comment]
Fixed in Tortuga.Chain.Core 1.0.6190.42922
