### ISSUE TITLE
Performance issue with SQL command builder

### ISSUE THREAD

**Issue by mikilion** [docevaad/Chain#183]
I encountered a performance issue, using the SQL command builder, when I run this query:
`SELECT CAST(CASE WHEN EXISTS (SELECT 1 FROM TableName WHERE Id = @Id AND Value = @Value) THEN 1 ELSE 0 END AS BIT)`
This is the Chain code snippet:
`ds.Sql(sqlStatement, new { @Id = id, @Value= value }).ToBoolean().`
where 'id' is integer type and 'value' is byte array type.
Entity Framework and SqlClient take half the time.

**Comment by Grauenwolf** [comment]
What are the data types? It could be var/nvar conversion issue.

**Comment by mikilion** [comment]
'Id' is int type and 'Value' is varbinary(max) type.

**Comment by Grauenwolf** [comment]
That'll take some research and profiling. I don't normally use varBinary so I'm not aware of all the tricks and traps.

**Comment by Grauenwolf** [comment]
I wasn't able to replicate the issue. The only time I saw a significant difference between Chain and ADO was when not reusing the data source (which will always be a problem).

```
// * Summary *

BenchmarkDotNet=v0.10.1, OS=Microsoft Windows NT 6.2.9200.0
Processor=Intel(R) Core(TM) i7-5500U CPU 2.40GHz, ProcessorCount=4
Frequency=2338337 Hz, Resolution=427.6544 ns, Timer=TSC
  [Host]     : Clr 4.0.30319.42000, 32bit LegacyJIT-v4.6.1586.0
  DefaultJob : Clr 4.0.30319.42000, 32bit LegacyJIT-v4.6.1586.0

        Method |        Mean |    StdDev | Allocated |
-------------- |------------ |---------- |---------- |
         Chain | 162.3104 us | 2.1740 us |   5.36 kB |
 Chain_NoCache | 334.3321 us | 4.5620 us |  12.86 kB |
   Chain_Async | 220.6475 us | 6.5868 us |   7.76 kB |
           Ado | 134.5543 us | 0.9192 us |   2.76 kB |
     Ado_Async | 184.8313 us | 0.3802 us |   4.38 kB |
     Ado_Typed | 135.1047 us | 0.7062 us |   2.75 kB |
```

Here's a branch with my test cases. 

https://github.com/docevaad/Chain/tree/Performance-issue-with-SQL-command-builder-183

https://github.com/docevaad/Chain/blob/Performance-issue-with-SQL-command-builder-183/Tortuga.Chain/PerformanceTest/Program.cs
