### ISSUE TITLE
 what about  .net framework 3.5  ?

### ISSUE THREAD

**Issue by athinboy** [docevaad/Chain#188]

**Comment by Grauenwolf** [comment]
Maybe if we created a version without any async support.

Are you just curious or is something keeping you on the old version of .NET?

**Comment by fgq841103** [comment]
Thanks for your reply!

I think Chain is so  good that i really want to taken it , sometimes,easier than  Dapper! But ,Server Machine with .Net 3.5  can not reboot anytime,on the other hand , lots of  projects is developed with old version  visual studio !
Sorry for my broken English!

**Comment by Grauenwolf** [comment]
I can't promise anything, but I will try to look at doing a .NET 3.5 version in March.
