### ISSUE TITLE
what about to  write sql to log system ?

### ISSUE THREAD

**Issue by athinboy** [docevaad/Chain#189]
for example : https://github.com/ef-labs/slf4net?

**Comment by Grauenwolf** [comment]
To setup a global SQL logger, start with this example:

        DataSource.GlobalExecutionFinished += DefaultDispatcher_ExecutionFinished;

        static void DefaultDispatcher_ExecutionFinished(object sender, ExecutionEventArgs e)
        {
            Debug.WriteLine("******");
            Debug.WriteLine($"Execution finished: {e.ExecutionDetails.OperationName}. Duration: {e.Duration.Value.TotalSeconds.ToString("N3")} sec. Rows affected: {(e.RowsAffected != null ? e.RowsAffected.Value.ToString("N0") : "<NULL>")}.");

            if (e.ExecutionDetails is SqlServerCommandExecutionToken)
            {
                Debug.WriteLine("");
                Debug.WriteLine("Command text: ");
                Debug.WriteLine(e.ExecutionDetails.CommandText);
                Debug.Indent();
                foreach (var item in ((SqlServerCommandExecutionToken)e.ExecutionDetails).Parameters)
                    Debug.WriteLine(item.ParameterName + ": " + (item.Value == null || item.Value == DBNull.Value ? "<NULL>" : item.Value));
                Debug.Unindent();
                Debug.WriteLine("******");
                Debug.WriteLine("");
            }
        }

There are also events for ExecutionStarted, ExecutionError, and ExecutionCanceled, 

***
If you want to log only a particular DataSource, use these events:

            dataSource.ExecutionCanceled += DefaultDispatcher_ExecutionCanceled;
            dataSource.ExecutionError += DefaultDispatcher_ExecutionError;
            dataSource.ExecutionFinished += DefaultDispatcher_ExecutionFinished;
            dataSource.ExecutionStarted += DefaultDispatcher_ExecutionStarted;

By default, a child data source created by `dataSource.BeginTransaction` or `dataSource.WithUser` will inherit the event handlers of the parent. So you don't have to worry about manually adding them after starting a transaction.

**Comment by Grauenwolf** [comment]
Is this sufficient for your needs?

**Comment by athinboy** [comment]
Thanks for you reply! But I need more.

I have some experience of java development  that operate DB with mybatis .  With the standard  log system, Operations staff and developers can set  output and  level of logging  conveniently, especially  for debug!
Maybe it is overclaim, i just give my advince!


Sorry For my broken English!

**Comment by Grauenwolf** [comment]
The basic idea is that you use those event handlers to wire it up to whatever logging framework you happen to be using. We don't want to force you to use a particular logging framework.

To do logging the way MyBatis does would require us to create a separate Nuget package for each logging framework. And that would be far too much effort. So unfortunately I have to say no.
