### ISSUE TITLE
SQL Server Nuget package doesnt work under .NET Standard

### ISSUE THREAD

**Issue by haefele** [docevaad/Chain#206]
Hi, I'm trying to use the SqlServerDataSource, but the nuget package for it doesnt provide a DLL for .net Standard.

**Comment by Grauenwolf** [comment]
That's odd. Unfortunately I won't be able to look at it right now as I'm getting ready for a trip.

**Comment by haefele** [comment]
I'm not very well versed with MSBuild scripts, but I guess it might be because [this part](https://github.com/docevaad/Chain/blob/master/Tortuga.Chain/Package.Tortuga.Chain.Core.msbuild#L84) is missing from the SqlServer build script [here](https://github.com/docevaad/Chain/blob/master/Tortuga.Chain/Package.Tortuga.Chain.SqlServer.msbuild#L72). 

I might give a pull-request a try if thats fine with you.

**Comment by Grauenwolf** [comment]
Sorry for the long delay, I've been on the road for way too long.

I've posted the updated NuGet package with the .NET Standard 1.3 version. I'm hoping to work on a .NET Standard 2.0 version this week, but I just found out that I'm travelling cross-country again.

**Comment by Grauenwolf** [comment]
Support for .NET Standard 2.0 has also been posted for SQL Server.
