### ISSUE TITLE
Null Ref Exception using ToCollection<T> that is not present in ToObject<T>

### ISSUE THREAD

**Issue by vbnet3d** [docevaad/Chain#213]
I have a simple POCO:

```
[Table("Items", Schema = "dbo")]
    public class Item
    {
        public string ItemNbr { get; set; } = "";
        public string CategoryID { get; set; } = "";
        public string ItemDesc { get; set; } = "";
        public string ItemContents { get; set; } = "";
        public decimal Price { get; set; } = 0.0M;
    }
```

The properties ItemNbr and CategoryID are the PK in the table.

I can load one with no problem using ToObject<Item>().Execute() when I set both values in my anonymous object. However, if I set only CategoryID in the anonymous object and then call ToCollection<T>, I get this error:

> Object reference not set to an instance of an object.

Nothing else is different, and I can't find any documentation addressing this. The InnerException is null.

**Comment by vbnet3d** [comment]
This is with Sql Server, btw.

**Comment by Grauenwolf** [comment]
Can you post a stack trace?

**Comment by Grauenwolf** [comment]
SQL generation for a single object or a collection is the same. So the problem is probably in the materializer. 

Hard to say what it could be though. PKs are only honored for update/delete operations. So that may be a red herring.

**Comment by Grauenwolf** [comment]
By the way, is the .NET Core? 

That has less testing and I've seen weird things in the past.

**Comment by Grauenwolf** [comment]
I can't reproduce the bug on .NET Standard or Core. This is what I used to attempt to find the problem:

```
    [Table("Items", Schema = "dbo")]
    public class Item
    {
        public string ItemNbr { get; set; } = "";
        public string CategoryID { get; set; } = "";
        public string ItemDesc { get; set; } = "";
        public string ItemContents { get; set; } = "";
        public decimal Price { get; set; } = 0.0M;
    }

    class Program
    {

        static string tableDef = @"
CREATE TABLE dbo.Items(
ItemNbr NVARCHAR(50) NOT NULL,
CategoryID NVARCHAR(50) NOT NULL,
ItemDesc NVARCHAR(50) NOT NULL,
ItemContents NVARCHAR(50) NOT NULL,
Price DECIMAL NOT NULL,
CONSTRAINT PK_Items PRIMARY KEY(ItemNbr, CategoryID)
)
";

        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");


            var DataSource = new SqlServerDataSource("data source=.;initial catalog=Test;integrated security=True");


            DataSource.DatabaseMetadata.PreloadTables();

            if (!DataSource.DatabaseMetadata.GetTablesAndViews().Any(t => t.Name == "dbo.Items"))
            {
                DataSource.Sql(tableDef).Execute();

                var list = new List<Item>();
                for (var i = 0; i < 100; i++)
                    for (var j = 0; j < 100; j++)
                    {
                        list.Add(new Item()
                        {
                            ItemNbr = "G" + i.ToString("000"),
                            CategoryID = "J" + j.ToString("000"),
                            ItemDesc = "G" + i.ToString("000") + "-" + "J" + j.ToString("000"),
                            Price = i + j * 0.01M
                        });

                    }

                DataSource.InsertBulk("dbo.Items", list).Execute();
            }

            var searchFilter = DataSource.From<Item>().ToString("CategoryID").Execute(); //grab any value

            var single1 = DataSource.From<Item>(new { CategoryID = searchFilter }).ToObject<Item>(RowOptions.DiscardExtraRows).Execute();
            var list1 = DataSource.From<Item>(new { CategoryID = searchFilter }).ToCollection<Item>().Execute();
        }
    }
```

**Comment by Grauenwolf** [comment]
Ok, so here's what I think the problem is.

1. You have nulls in the `Price` column.
2. Your `Price` property is non-nullable.
3. There is a "fast mode" for `ToCollection()` that wasn't handling assigning nulls to non-nullable properties correctly.
4. When searching by ItemNbr and CategoryID, you just happened to pick a record with a non-null `Price`.

If these assumptions are correct, either of the below fixes will solve the problem.

A: Make `Price` nullable. 
B: Upgrade to Tortuga.Chain.Core.1.2.6558.39990 (https://www.nuget.org/packages/Tortuga.Chain.Core/1.2.6558.39990)

If this doesn't solve your problem, feel free to reopen the ticket.

**Comment by vbnet3d** [comment]
I am pleased to say that this fixes the issue! Thanks so much for looking at this so quick! I really like what you've done with this library, and I was hoping it would work on my database - It's a system that has grown over about a decade, and there are things like NULL columns where it doesn't really make sense, but those records are grandfathered in.

**Comment by Grauenwolf** [comment]
If you run into any other problems don't hesitate to ask. 

One of the goals is for this to work on any database, not just new ones built specifically for it. So we like having weird scenarios to test against.
