### ISSUE TITLE
Bulk Insert for MySQL

### ISSUE THREAD

**Issue by Grauenwolf** [docevaad/Chain#229]
https://stackoverflow.com/questions/4883376/how-to-bulk-insert-into-mysql-using-c-sharp

**Comment by Grauenwolf** [comment]
This will require writing to a CSV file, then loading back.

**Comment by Grauenwolf** [comment]
Which in turn means that we need a CSV writer.

**Comment by ewinnington** [comment]
Did you look at MySqlConnector’s implementation of the bulk [loader](
https://github.com/mysql-net/MySqlConnector/blob/69080de2b4e1ceddeb105bf3244de1f5a30cede7/src/MySqlConnector/MySql.Data.MySqlClient/MySqlBulkLoader.cs)? Supposedly they allow stream import into MySQL.

Which MySQL driver you use?

**Comment by Grauenwolf** [comment]
I'm currently using `MySql.Data`. I need to verify that has a .NET Core version though.

**Comment by Grauenwolf** [comment]
I'm currently using MySQL.Data. Is that ok or would you recommend something else?

https://www.nuget.org/packages/MySql.Data

**Comment by Grauenwolf** [comment]
Actually, I'm really liking what I'm seeing in that MySqlConnector project you posted. I wonder how hard it would be to swap MySQL.Data for MySqlConnector.

**Comment by ewinnington** [comment]
I must admit that with C#, I’ve never used MySQL or MariaDB. All my MySQL experiences dates back to the end of the ‘90s on a LAMP stack.so I don’t know which connector is best. 

I was googling for bulk, stream and MySQL when I came upon their project and saw they had a bulk insert.

**Comment by Grauenwolf** [comment]
@ewinnington Thank you for the recommendation. We did end up using MySqlConnector for our database driver and it worked brilliantly. 

Which means we don't have to write a file to disk, though we still have to generate an in-memory stream of CSV data.
