### ISSUE TITLE
Batch insert for SQLite

### ISSUE THREAD

**Issue by Grauenwolf** [docevaad/Chain#235]
We might be able to use UNION ALL.

https://stackoverflow.com/questions/1609637/is-it-possible-to-insert-multiple-rows-at-a-time-in-an-sqlite-database

The question is, can we do this and still make it parameterized? If not, how hard is it to properly escape values for SQLite so we don't create a SQL injection vulnerability?

**Comment by Grauenwolf** [comment]
The other method is to implicitly open a transaction. 

We don't want to do this because it may interfere with transactions the user has already opened.

**Comment by ewinnington** [comment]
You could use a SAVEPOINT to create a transaction, which allows nesting inside a previous transaction, RELEASE upon finishing.

**Comment by Grauenwolf** [comment]
That would require changing some of the internals for the DataSource classes, but I do find the idea interesting.

**Comment by Grauenwolf** [comment]
And maybe I'm overthinking it. 

The execution token already has a "LockType" property. I can see adding another property called "RequiresTransaction" that would automatically create one if it doesn't already exist.

The more I think about this, the smaller the change seems.

**Comment by Grauenwolf** [comment]
Reference: https://sqlite.org/lang_savepoint.html
