### ISSUE TITLE
SqlDependency in .NET Standard

### ISSUE THREAD

**Issue by chucker** [docevaad/Chain#247]
SqlDependency support is currently disabled for .NET Standard 2.0:

```xml
<DefineConstants>$(DefineConstants);OleDb_Missing;SqlDependency_Missing;System_Configuration_Missing</DefineConstants>
```

However, that project depends on `System.Data.SqlClient` version 4.5.1, which [does appear to include](https://github.com/dotnet/corefx/pull/20708) SqlDependency support. Is this constant outdated?

**Comment by Grauenwolf** [comment]
I was not aware of that. When we do the next version of this we'll be sure to enable SqlDependency for .NET Standard.
