### ISSUE TITLE
Table names not quoted and causing syntax error in SQLite

### ISSUE THREAD

**Issue by chadunit** [docevaad/Chain#261]
Hi, just trying this out with SQLite and noticed table names are not quoted in the generated SQL and can produce syntax errors. Poking through the code it seems names are quoted for other vendors so maybe this is just an oversight. For reference here is the [SQLite page on quoting](https://www.sqlite.org/lang_keywords.html).

Here is an example using a table named `table` -- see comment indicating SQLite error. Code is F# but I'm sure the issue is obvious regardless of language.

```fsharp
open Tortuga.Chain
open Tortuga.Chain.SQLite

// model
type Table = { id : int64 }

// create database with a table named "table"
let chain = SQLiteDataSource("Data Source=TestChain.db;Version=3;")
chain.Sql("DROP TABLE IF EXISTS \"table\";").Execute() |> ignore
chain.Sql("CREATE TABLE \"table\" (id INTEGER PRIMARY KEY);").Execute() |> ignore

// ***********************************************************
// SQLite error (1): near "table": syntax error
// ***********************************************************
chain.Insert(SQLiteObjectName("table"), { id = 1L }).AsNonQuery().Execute() |> ignore

// works as raw sql with quoted table name
chain.Sql("INSERT INTO \"table\" (id) VALUES (@id)", { id = 2L }).Execute() |> ignore
```

(Edit: F# note moved to https://github.com/docevaad/Chain/issues/262.)

**Comment by Grauenwolf** [comment]
Please open a separate ticket for the F# compatibility problem. I don't foresee any problems with adding those overloads.

**Comment by Grauenwolf** [comment]
I'm traveling today, but I should be able to fix the quoting bug in SQLite tomorrow night. Quoting is handled in two places and testing should be easy.

**Comment by Grauenwolf** [comment]
Fixed in Tortuga.Chain.SQLite.2.1.6980.35218.nupkg
