### ISSUE TITLE
Is it possible to receive the primary key after upsert (in case of a insert aftera all)

### ISSUE THREAD

**Issue by uwerichter** [docevaad/Chain#380]
Something like that:  
` long pk =     DB.Upsert(TableName, data).Execute();`

Because need to now the (new aka last key-Value)

**Comment by Grauenwolf** [comment]
I'm not near a computer to test, but this should work:

    long pk = DB.Upsert(TableName, data).ToInt64().Execute();

The basic idea is that after any operation, even delete, you can ask for information using a `ToXxx` method.

**Comment by uwerichter** [comment]
> I'm not near a computer to test, but this should work:
> 
> ```
> long pk = DB.Upsert(TableName, data).ToInt64().Execute();
> ```
> 
> The basic idea is that after any operation, even delete, you can ask for information using a `ToXxx` method.

This does the job - really great. Thx a lot and stay healthy!

**Comment by Grauenwolf** [comment]
You're welcome.
