### ISSUE TITLE
Can't exec sql server system procedures like sp_sequence_get_range

### ISSUE THREAD

**Issue by agrinei** [docevaad/Chain#382]
Tortuga.Chain.SqlServer v. 3.3.2 (but it happens with version 1.1 too)

Maybe this is not an issue but I couldn't find any documentation about it.
I'm trying to exec the sp_sequence_get_range stored procedure on sql server 2016 and it's failing with the message "Could not find stored procedure sp_sequence_get_range"

ds.Procedure("sp_sequence_get_range", parameters).Execute();

Using sql profiler I've noticed that the library is looking for the procedure in SYS.procedures

exec sp_executesql N'SELECT
s.name AS SchemaName,
sp.name AS Name,
sp.object_id AS ObjectId
FROM SYS.procedures sp
INNER JOIN sys.schemas s ON sp.schema_id = s.schema_id
WHERE s.name = @Schema AND sp.Name = @Name',N'@Schema nvarchar(3),@Name nvarchar(21)',@Schema=N'dbo',@Name=N'sp_sequence_get_range'

Maybe this is by design or some limitation, or just needs to be implemented.

Another question I have is if OUTPUT parameters are supported.

Thanks in advance!

**Comment by Grauenwolf** [comment]
Master stored procedures are not currently supported, but I'll see what I can do.

Since there are a lot of output parameters for this, would you like them all just as one dictionary?

Other options for capturing the output parameters would be populating an object or assigning values to variables one of the time (`.OutParameter(name, x => myX)`).

**Comment by Grauenwolf** [comment]
Ref: https://docs.microsoft.com/en-us/sql/relational-databases/system-stored-procedures/sp-sequence-get-range-transact-sql?view=sql-server-ver15

**Comment by agrinei** [comment]
I think that output parameters should update the argument object or the dictionary keys.

**Comment by Grauenwolf** [comment]
I like that.

**Comment by Grauenwolf** [comment]
Ok, this is pretty messy.

1. We have to be smart enough to add "sys." instead of the user's default schema
2. We need to check `sys.all_objects/sys.all_parameters` because system stored procedures don't show up in `sys.procedures/sys.parameters`
3. But if you're using an older version of SQL Server, then `sys.all_objects/sys.all_parameters` doesn't exist.
4. If this doesn't work, then we also need to check the master database
5. But if you're on Azure, you need a separate connection to read from `master` because cross-database calls aren't allowed.
6. And if the user cannot connect to master, it still needs to return our normal "cannot find X" error message.

@agrinei , you've certainly given me a tricky puzzle.

**Comment by Grauenwolf** [comment]
Work-around:

Use `.Sql` instead of `.Procedure`.
Manually create the list of parameters, explicitly adding the output parameters.

```
                var parameters = new List<SqlParameter>()
                {
                    new SqlParameter("@sequence_name", "dbo.TestSequence"),
                    new SqlParameter("@range_size", "10"),
                    new SqlParameter("@range_first_value", DBNull.Value){ SqlDbType= SqlDbType.Variant, Direction=ParameterDirection.Output},
                    new SqlParameter("@range_last_value", DBNull.Value){ SqlDbType= SqlDbType.Variant, Direction=ParameterDirection.Output},
                    new SqlParameter("@range_cycle_count", DBNull.Value){ SqlDbType= SqlDbType.Int, Direction=ParameterDirection.Output},
                    new SqlParameter("@sequence_increment", DBNull.Value){ SqlDbType= SqlDbType.Variant, Direction=ParameterDirection.Output},
                    new SqlParameter("@sequence_min_value", DBNull.Value){ SqlDbType= SqlDbType.Variant, Direction=ParameterDirection.Output},
                    new SqlParameter("@sequence_max_value", DBNull.Value){ SqlDbType= SqlDbType.Variant, Direction=ParameterDirection.Output},
                };

                await dataSource.Sql(@"EXEC sys.sp_sequence_get_range @sequence_name = @sequence_name,
                               @range_size = @range_size,
                               @range_first_value = @range_first_value OUTPUT,
                               @range_last_value = @range_last_value OUTPUT,
                               @range_cycle_count = @range_cycle_count OUTPUT,
                               @sequence_increment = @sequence_increment OUTPUT,
                               @sequence_min_value = @sequence_min_value OUTPUT,
                               @sequence_max_value = @sequence_max_value OUTPUT;", parameters).ExecuteAsync();

                var rangeFirstValue = parameters.Single(p => p.ParameterName == "@range_first_value").Value;
                Assert.IsTrue((long)rangeFirstValue > 0);
```

**Comment by Grauenwolf** [comment]
Chain 3.4 syntax with support for system and master stored procedures.

If ignoring output parameters

```
await dataSource.Procedure("sys.sp_sequence_get_range", new { @sequence_name = "dbo.TestSequence", @range_size = 10 }).ExecuteAsync();
```

If capturing output parameters

```
var parameters = new List<SqlParameter>()
{
    new SqlParameter("@sequence_name", "dbo.TestSequence"),
    new SqlParameter("@range_size", "10"),
    new SqlParameter("@range_first_value", DBNull.Value){ SqlDbType= SqlDbType.Variant, Direction=ParameterDirection.Output},
    new SqlParameter("@range_last_value", DBNull.Value){ SqlDbType= SqlDbType.Variant, Direction=ParameterDirection.Output},
    new SqlParameter("@range_cycle_count", DBNull.Value){ SqlDbType= SqlDbType.Int, Direction=ParameterDirection.Output},
    new SqlParameter("@sequence_increment", DBNull.Value){ SqlDbType= SqlDbType.Variant, Direction=ParameterDirection.Output},
    new SqlParameter("@sequence_min_value", DBNull.Value){ SqlDbType= SqlDbType.Variant, Direction=ParameterDirection.Output},
    new SqlParameter("@sequence_max_value", DBNull.Value){ SqlDbType= SqlDbType.Variant, Direction=ParameterDirection.Output},
};

await dataSource.Sql(@"EXEC sys.sp_sequence_get_range @sequence_name = @sequence_name,
                @range_size = @range_size,
                @range_first_value = @range_first_value OUTPUT,
                @range_last_value = @range_last_value OUTPUT,
                @range_cycle_count = @range_cycle_count OUTPUT,
                @sequence_increment = @sequence_increment OUTPUT,
                @sequence_min_value = @sequence_min_value OUTPUT,
                @sequence_max_value = @sequence_max_value OUTPUT;", parameters).ExecuteAsync();

var rangeFirstValue = parameters.Single(p => p.ParameterName == "@range_first_value").Value;
Assert.IsTrue((long)rangeFirstValue > 0);
```

Next step: remove the need to manually create output parameters.

**Comment by agrinei** [comment]
Sorry, I couldn't imagine it would be this mess :/
Your workaround is really great.

In my case I have created a procedure to map the single output parameter I was interested in to a return parameter:

create procedure usp_sequence_get_range  @sequence_name nvarchar(776), @range_size bigint
AS 
BEGIN
	declare @range_first_value sql_variant
	EXEC sys.sp_sequence_get_range @sequence_name, @range_size, @range_first_value OUTPUT
	select @range_first_value
END

ds.Procedure("usp_sequence_get_range", new { sequence_name, range_size }).ToInt64().ExecuteAsync()

And it's already running in production :)
By the way, I'm still on Chain v. 1.1.0
I will upgrade to v. 3.4 when it's released!

Thank you very much for your support.

**Comment by Grauenwolf** [comment]
It's a fun challenge, especially now that I know the work-around is acceptable and I don't have to rush. 

Capture as Object Output

```
var result = await dataSource.Procedure("sys.sp_sequence_get_range", new { sequence_name = "dbo.TestSequence", range_size = 10 }).AsOutputs<SequenceGetRangeResult>().ExecuteAsync();

Assert.IsTrue(result.range_first_value > 0);
```

Capture as Dictionary Output

```
var result = await dataSource.Procedure("sys.sp_sequence_get_range", new { sequence_name = "dbo.TestSequence", range_size = 10 }).AsOutputs().ExecuteAsync();

Assert.IsTrue(result.ContainsKey("range_first_value"));
Assert.IsTrue((long)result["range_first_value"] > 0);
```

Next steps: Refresh the original parameter object instead of creating a new one.

**Comment by agrinei** [comment]
Nice!! :-)

**Comment by Grauenwolf** [comment]
I'm running the last set of tests today. Sorry for the long delay, but Chain 3.4 with the enhancement you requested should be published soon.

**Comment by Grauenwolf** [comment]
If there's anything you want in the next round, let me know.

**Comment by agrinei** [comment]
Thank you, I appreciated it! I'm still using the workaround I've shown you above, it works great. I plan to upgrade the package when I migrate to .Net 5.0 (from 3.1). By the way, do you have plans to have a release targeting net5.0 ?

**Comment by Grauenwolf** [comment]
Not at this time. When I added a .NET 5.0 target, the compiler was acting kinda wonky so I'm going to give them some time to work out the bugs. But you should be able to use the .NET Standard 2.1 DLLs in .NET 5.0 without a problem.

**Comment by agrinei** [comment]
Yeah, I'm gonna wait a couple of weeks so they can fix some bugs too. I'll go with .Net Standard 2.1 then, no problem. Thank you again for your great work.
