### ISSUE TITLE
Tortuga.Chain.Mysql with .Net Framework

### ISSUE THREAD

**Issue by njihiarichard** [docevaad/Chain#386]
I get the following error when using Tortuga.Chain.Mysql with .Net Framework 4.7

> System.TypeInitializationException
  HResult=0x80131534
  Message=The type initializer for 'Tortuga.Chain.DataSources.DataSource' threw an exception.
  Source=Tortuga.Chain.Core
  StackTrace:
   at Tortuga.Chain.DataSources.DataSource.get_DefaultCache()
   at Tortuga.Chain.MySqlDataSource..ctor(String name, String connectionString, MySqlDataSourceSettings settings)
   at Tortuga.Chain.MySqlDataSource..ctor(String connectionString, MySqlDataSourceSettings settings)

Inner Exception 1:
FileNotFoundException: Could not load file or assembly '**System.X.X**, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.

Where System.X.X is System.Runtime.Caching, System.Threading etc.

Initialization is 
`dataSource = new MySqlDataSource("server = servername; uid = username; pwd = password; database = mydb");`

**Comment by Grauenwolf** [comment]
That's a fun one. There's lots of reasons Visual Studio can glitch and cause that kind of error. Some of the things that have worked for me in the past include...

* Close VS, then delete all "bin" and "obj" folders.
* Reinstall the package, which should trigger a reload of any dependencies. https://docs.microsoft.com/en-us/nuget/consume-packages/reinstalling-and-updating-packages
* Delete all of your binding redirects in app.config. Then in the project file add:

  <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
  <GenerateBindingRedirectsOutputType>true</GenerateBindingRedirectsOutputType>

ref: https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/how-to-enable-and-disable-automatic-binding-redirection

**Comment by Grauenwolf** [comment]
While it's not a guarantee, this seems to happen a lot less when I'm using the new style C# csproj files, even if I'm targeting .NET 4.x. 

New style csproj files don't list all of the files. Here are a couple of examples,

https://github.com/docevaad/Chain/blob/master/Tortuga.Chain/Tortuga.Chain.Core/Tortuga.Chain.Core.csproj
https://github.com/docevaad/Chain/blob/master/Tortuga.Chain/Tortuga.Chain.MySql/Tortuga.Chain.MySql.csproj

**Comment by njihiarichard** [comment]
Hi,
I resolved this issue by removing the UI (Old Project) and recreating the project targeting the same version as the Data Access Library, then re-importing over the project files. Thank you for the pointers as they came in handy before making this decision.

**Comment by Grauenwolf** [comment]
I'm glad it worked out for you. I know what a headache that problem can be.
