### ISSUE TITLE
CSV Import Support

### ISSUE THREAD

**Issue by Grauenwolf** [docevaad/Chain#49]
Basic support for importing CSV files. This should work alone and in conjunction with bulk insert.

**Comment by Grauenwolf** [comment]
Does this live in Core or in a separate library?

**Comment by docevaad** [comment]
Are there any other file formats we're looking to support?

**Comment by Grauenwolf** [comment]
Not right away. CSV is the big one that everyone uses.

Flattening out a JSON file would be cool, but that's a research project on its own.

-----Original Message-----

**Comment by Grauenwolf** [comment]
CSV manipulation is too far removed from our core goals. Maybe we'll look into it again another day if we're interested in implementing a DbConnection/DbCommand for text files complete with SQL parser. (Yea, probably not going to happen.)
