### ISSUE TITLE
Generics and compiled materializers

### ISSUE THREAD

**Issue by Grauenwolf** [docevaad/Chain#64]
Compiled materializers do not currently support generic types (other than Nullable<T>). 

The problem is that Type.FullName does not produce a C# compatible type name. We'll have to build a mapper that correctly renders the name.

**Comment by adamclifford** [comment]
What about using [Type.AssemblyQualifiedName()](https://msdn.microsoft.com/en-us/library/system.type.assemblyqualifiedname.aspx) as it includes the assembly too.

[See this article for a fuller explanation](http://thirteendaysaweek.com/2013/11/05/loading-types-from-strings-in-c-sharp/)

**Comment by Grauenwolf** [comment]
That won't work with our current runtime code generator. If I were using raw IL it would be fine, but we're using the Roslyn/C# parser.

**Comment by Grauenwolf** [comment]
Reference: http://stackoverflow.com/questions/41355397/how-to-i-convert-from-type-fullname-to-a-c-sharp-type-name

**Comment by Grauenwolf** [comment]
Version 1.1.
